name: generate-documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: sersoft-gmbh/SwiftyActions@v1
      with:
        platform:    ubuntu-20.04
        branch-name: main
        version-tag: swift-DEVELOPMENT-SNAPSHOT-2021-05-18-a
    
    - run: infrastructure/generate-documentation
    
    - uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: documentation/ 
