name: generate-documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    #- uses: YOCKOW/Action-setup-swift@v1
    
    - run: infrastructure/swift-setup 
    - run: infrastructure/generate-documentation
    
    - uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: documentation/ 
