name: generate-documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # uses .swift-version
    - uses: YOCKOW/Action-setup-swift@master
    
    # fix runpath issue 
    - run: chrpath -r '$ORIGIN/../linux' $SWIFTENV_ROOT/versions/$(cat .swift-version)/usr/lib/swift/pm/libPackagePlugin.so
      
    - run: Infrastructure/generate-documentation
    
    - uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: documentation/ 
